[package]
name = "leitha"
version = "0.1.0"
authors = ["Diku-chan <kdv99@mail.ru>"]
edition = "2018"

[dependencies]
reqwest = "0.9.10"
select = "0.4.2"
scraper = "0.9.1"
clap = "2.32.0"
serde = "1.0.89"
serde_derive = "1.0.89"
serde_json = "1.0.39"