[package]
name = "leitha"
version = "0.1.1"
authors = ["Diku-chan <kdv99@mail.ru>"]
edition = "2018"

[dependencies]
select = "0.4.2"
scraper = "0.9.1"
reqwest = "0.9.10"
clap = "2.32.0"
serde = "1.0.89"
serde_derive = "1.0.89"
serde_json = "1.0.39"
ws = "0.8.1"
env_logger = "0.6.1"